version: '3.10'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - internal

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - web
    command: http web:8000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
